apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-operator
spec:
  selector:
    matchLabels:
      app: my-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: my-operator
    spec:
      containers:
      - name: my-operator
        image: YOUR_DOCKER_REGISTRY/my-operator:latest # Replace with your Docker image
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: my-operator
spec:
  selector:
    app: my-operator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
